/* automatically generated by rust-bindgen 0.69.4 */

pub const ANARI_UNKNOWN: ::std::os::raw::c_int = 0;
pub const ANARI_DATA_TYPE: ::std::os::raw::c_int = 100;
pub const ANARI_STRING: ::std::os::raw::c_int = 101;
pub const ANARI_VOID_POINTER: ::std::os::raw::c_int = 102;
pub const ANARI_BOOL: ::std::os::raw::c_int = 103;
pub const ANARI_STRING_LIST: ::std::os::raw::c_int = 150;
pub const ANARI_DATA_TYPE_LIST: ::std::os::raw::c_int = 151;
pub const ANARI_PARAMETER_LIST: ::std::os::raw::c_int = 152;
pub const ANARI_FUNCTION_POINTER: ::std::os::raw::c_int = 200;
pub const ANARI_MEMORY_DELETER: ::std::os::raw::c_int = 201;
pub const ANARI_STATUS_CALLBACK: ::std::os::raw::c_int = 202;
pub const ANARI_LIBRARY: ::std::os::raw::c_int = 500;
pub const ANARI_DEVICE: ::std::os::raw::c_int = 501;
pub const ANARI_OBJECT: ::std::os::raw::c_int = 502;
pub const ANARI_ARRAY: ::std::os::raw::c_int = 503;
pub const ANARI_ARRAY1D: ::std::os::raw::c_int = 504;
pub const ANARI_ARRAY2D: ::std::os::raw::c_int = 505;
pub const ANARI_ARRAY3D: ::std::os::raw::c_int = 506;
pub const ANARI_CAMERA: ::std::os::raw::c_int = 507;
pub const ANARI_FRAME: ::std::os::raw::c_int = 508;
pub const ANARI_GEOMETRY: ::std::os::raw::c_int = 509;
pub const ANARI_GROUP: ::std::os::raw::c_int = 510;
pub const ANARI_INSTANCE: ::std::os::raw::c_int = 511;
pub const ANARI_LIGHT: ::std::os::raw::c_int = 512;
pub const ANARI_MATERIAL: ::std::os::raw::c_int = 513;
pub const ANARI_RENDERER: ::std::os::raw::c_int = 514;
pub const ANARI_SURFACE: ::std::os::raw::c_int = 515;
pub const ANARI_SAMPLER: ::std::os::raw::c_int = 516;
pub const ANARI_SPATIAL_FIELD: ::std::os::raw::c_int = 517;
pub const ANARI_VOLUME: ::std::os::raw::c_int = 518;
pub const ANARI_WORLD: ::std::os::raw::c_int = 519;
pub const ANARI_INT8: ::std::os::raw::c_int = 1000;
pub const ANARI_INT8_VEC2: ::std::os::raw::c_int = 1001;
pub const ANARI_INT8_VEC3: ::std::os::raw::c_int = 1002;
pub const ANARI_INT8_VEC4: ::std::os::raw::c_int = 1003;
pub const ANARI_UINT8: ::std::os::raw::c_int = 1004;
pub const ANARI_UINT8_VEC2: ::std::os::raw::c_int = 1005;
pub const ANARI_UINT8_VEC3: ::std::os::raw::c_int = 1006;
pub const ANARI_UINT8_VEC4: ::std::os::raw::c_int = 1007;
pub const ANARI_INT16: ::std::os::raw::c_int = 1008;
pub const ANARI_INT16_VEC2: ::std::os::raw::c_int = 1009;
pub const ANARI_INT16_VEC3: ::std::os::raw::c_int = 1010;
pub const ANARI_INT16_VEC4: ::std::os::raw::c_int = 1011;
pub const ANARI_UINT16: ::std::os::raw::c_int = 1012;
pub const ANARI_UINT16_VEC2: ::std::os::raw::c_int = 1013;
pub const ANARI_UINT16_VEC3: ::std::os::raw::c_int = 1014;
pub const ANARI_UINT16_VEC4: ::std::os::raw::c_int = 1015;
pub const ANARI_INT32: ::std::os::raw::c_int = 1016;
pub const ANARI_INT32_VEC2: ::std::os::raw::c_int = 1017;
pub const ANARI_INT32_VEC3: ::std::os::raw::c_int = 1018;
pub const ANARI_INT32_VEC4: ::std::os::raw::c_int = 1019;
pub const ANARI_UINT32: ::std::os::raw::c_int = 1020;
pub const ANARI_UINT32_VEC2: ::std::os::raw::c_int = 1021;
pub const ANARI_UINT32_VEC3: ::std::os::raw::c_int = 1022;
pub const ANARI_UINT32_VEC4: ::std::os::raw::c_int = 1023;
pub const ANARI_INT64: ::std::os::raw::c_int = 1024;
pub const ANARI_INT64_VEC2: ::std::os::raw::c_int = 1025;
pub const ANARI_INT64_VEC3: ::std::os::raw::c_int = 1026;
pub const ANARI_INT64_VEC4: ::std::os::raw::c_int = 1027;
pub const ANARI_UINT64: ::std::os::raw::c_int = 1028;
pub const ANARI_UINT64_VEC2: ::std::os::raw::c_int = 1029;
pub const ANARI_UINT64_VEC3: ::std::os::raw::c_int = 1030;
pub const ANARI_UINT64_VEC4: ::std::os::raw::c_int = 1031;
pub const ANARI_FIXED8: ::std::os::raw::c_int = 1032;
pub const ANARI_FIXED8_VEC2: ::std::os::raw::c_int = 1033;
pub const ANARI_FIXED8_VEC3: ::std::os::raw::c_int = 1034;
pub const ANARI_FIXED8_VEC4: ::std::os::raw::c_int = 1035;
pub const ANARI_UFIXED8: ::std::os::raw::c_int = 1036;
pub const ANARI_UFIXED8_VEC2: ::std::os::raw::c_int = 1037;
pub const ANARI_UFIXED8_VEC3: ::std::os::raw::c_int = 1038;
pub const ANARI_UFIXED8_VEC4: ::std::os::raw::c_int = 1039;
pub const ANARI_FIXED16: ::std::os::raw::c_int = 1040;
pub const ANARI_FIXED16_VEC2: ::std::os::raw::c_int = 1041;
pub const ANARI_FIXED16_VEC3: ::std::os::raw::c_int = 1042;
pub const ANARI_FIXED16_VEC4: ::std::os::raw::c_int = 1043;
pub const ANARI_UFIXED16: ::std::os::raw::c_int = 1044;
pub const ANARI_UFIXED16_VEC2: ::std::os::raw::c_int = 1045;
pub const ANARI_UFIXED16_VEC3: ::std::os::raw::c_int = 1046;
pub const ANARI_UFIXED16_VEC4: ::std::os::raw::c_int = 1047;
pub const ANARI_FIXED32: ::std::os::raw::c_int = 1048;
pub const ANARI_FIXED32_VEC2: ::std::os::raw::c_int = 1049;
pub const ANARI_FIXED32_VEC3: ::std::os::raw::c_int = 1050;
pub const ANARI_FIXED32_VEC4: ::std::os::raw::c_int = 1051;
pub const ANARI_UFIXED32: ::std::os::raw::c_int = 1052;
pub const ANARI_UFIXED32_VEC2: ::std::os::raw::c_int = 1053;
pub const ANARI_UFIXED32_VEC3: ::std::os::raw::c_int = 1054;
pub const ANARI_UFIXED32_VEC4: ::std::os::raw::c_int = 1055;
pub const ANARI_FIXED64: ::std::os::raw::c_int = 1056;
pub const ANARI_FIXED64_VEC2: ::std::os::raw::c_int = 1057;
pub const ANARI_FIXED64_VEC3: ::std::os::raw::c_int = 1058;
pub const ANARI_FIXED64_VEC4: ::std::os::raw::c_int = 1059;
pub const ANARI_UFIXED64: ::std::os::raw::c_int = 1060;
pub const ANARI_UFIXED64_VEC2: ::std::os::raw::c_int = 1061;
pub const ANARI_UFIXED64_VEC3: ::std::os::raw::c_int = 1062;
pub const ANARI_UFIXED64_VEC4: ::std::os::raw::c_int = 1063;
pub const ANARI_FLOAT16: ::std::os::raw::c_int = 1064;
pub const ANARI_FLOAT16_VEC2: ::std::os::raw::c_int = 1065;
pub const ANARI_FLOAT16_VEC3: ::std::os::raw::c_int = 1066;
pub const ANARI_FLOAT16_VEC4: ::std::os::raw::c_int = 1067;
pub const ANARI_FLOAT32: ::std::os::raw::c_int = 1068;
pub const ANARI_FLOAT32_VEC2: ::std::os::raw::c_int = 1069;
pub const ANARI_FLOAT32_VEC3: ::std::os::raw::c_int = 1070;
pub const ANARI_FLOAT32_VEC4: ::std::os::raw::c_int = 1071;
pub const ANARI_FLOAT64: ::std::os::raw::c_int = 1072;
pub const ANARI_FLOAT64_VEC2: ::std::os::raw::c_int = 1073;
pub const ANARI_FLOAT64_VEC3: ::std::os::raw::c_int = 1074;
pub const ANARI_FLOAT64_VEC4: ::std::os::raw::c_int = 1075;
pub const ANARI_UFIXED8_RGBA_SRGB: ::std::os::raw::c_int = 2003;
pub const ANARI_UFIXED8_RGB_SRGB: ::std::os::raw::c_int = 2002;
pub const ANARI_UFIXED8_RA_SRGB: ::std::os::raw::c_int = 2001;
pub const ANARI_UFIXED8_R_SRGB: ::std::os::raw::c_int = 2000;
pub const ANARI_INT32_BOX1: ::std::os::raw::c_int = 2004;
pub const ANARI_INT32_BOX2: ::std::os::raw::c_int = 2005;
pub const ANARI_INT32_BOX3: ::std::os::raw::c_int = 2006;
pub const ANARI_INT32_BOX4: ::std::os::raw::c_int = 2007;
pub const ANARI_FLOAT32_BOX1: ::std::os::raw::c_int = 2008;
pub const ANARI_FLOAT32_BOX2: ::std::os::raw::c_int = 2009;
pub const ANARI_FLOAT32_BOX3: ::std::os::raw::c_int = 2010;
pub const ANARI_FLOAT32_BOX4: ::std::os::raw::c_int = 2011;
pub const ANARI_FLOAT64_BOX1: ::std::os::raw::c_int = 2208;
pub const ANARI_FLOAT64_BOX2: ::std::os::raw::c_int = 2209;
pub const ANARI_FLOAT64_BOX3: ::std::os::raw::c_int = 2210;
pub const ANARI_FLOAT64_BOX4: ::std::os::raw::c_int = 2211;
pub const ANARI_UINT64_REGION1: ::std::os::raw::c_int = 2104;
pub const ANARI_UINT64_REGION2: ::std::os::raw::c_int = 2105;
pub const ANARI_UINT64_REGION3: ::std::os::raw::c_int = 2106;
pub const ANARI_UINT64_REGION4: ::std::os::raw::c_int = 2107;
pub const ANARI_FLOAT32_MAT2: ::std::os::raw::c_int = 2012;
pub const ANARI_FLOAT32_MAT3: ::std::os::raw::c_int = 2013;
pub const ANARI_FLOAT32_MAT4: ::std::os::raw::c_int = 2014;
pub const ANARI_FLOAT32_MAT2x3: ::std::os::raw::c_int = 2015;
pub const ANARI_FLOAT32_MAT3x4: ::std::os::raw::c_int = 2016;
pub const ANARI_FLOAT32_QUAT_IJKW: ::std::os::raw::c_int = 2017;
pub const ANARI_FRAME_COMPLETION_CALLBACK: ::std::os::raw::c_int = 203;
pub const ANARI_INVALID_HANDLE: ::std::os::raw::c_int = 0;
pub const ANARI_SDK_VERSION_MAJOR: ::std::os::raw::c_int = 0;
pub const ANARI_SDK_VERSION_MINOR: ::std::os::raw::c_int = 10;
pub const ANARI_SDK_VERSION_PATCH: ::std::os::raw::c_int = 0;
pub const ANARI_LOG_DEBUG: ::std::os::raw::c_int = 1;
pub const ANARI_LOG_INFO: ::std::os::raw::c_int = 2;
pub const ANARI_LOG_WARNING: ::std::os::raw::c_int = 3;
pub const ANARI_LOG_ERROR: ::std::os::raw::c_int = 4;
pub const ANARI_LOG_NONE: ::std::os::raw::c_int = 5;
pub const ANARI_NO_WAIT: ::std::os::raw::c_uint = 0;
pub const ANARI_WAIT: ::std::os::raw::c_uint = 1;
pub const ANARI_STATUS_NO_ERROR: ::std::os::raw::c_int = 0;
pub const ANARI_STATUS_UNKNOWN_ERROR: ::std::os::raw::c_int = 1;
pub const ANARI_STATUS_INVALID_ARGUMENT: ::std::os::raw::c_int = 2;
pub const ANARI_STATUS_INVALID_OPERATION: ::std::os::raw::c_int = 3;
pub const ANARI_STATUS_OUT_OF_MEMORY: ::std::os::raw::c_int = 4;
pub const ANARI_STATUS_UNSUPPORTED_DEVICE: ::std::os::raw::c_int = 5;
pub const ANARI_STATUS_VERSION_MISMATCH: ::std::os::raw::c_int = 6;
pub const ANARI_SEVERITY_FATAL_ERROR: ::std::os::raw::c_int = 1;
pub const ANARI_SEVERITY_ERROR: ::std::os::raw::c_int = 2;
pub const ANARI_SEVERITY_WARNING: ::std::os::raw::c_int = 3;
pub const ANARI_SEVERITY_PERFORMANCE_WARNING: ::std::os::raw::c_int = 4;
pub const ANARI_SEVERITY_INFO: ::std::os::raw::c_int = 5;
pub const ANARI_SEVERITY_DEBUG: ::std::os::raw::c_int = 6;
pub type ANARIDataType = ::std::os::raw::c_int;
pub type ANARILogLevel = ::std::os::raw::c_int;
pub type ANARIWaitMask = ::std::os::raw::c_uint;
pub type ANARIStatusCode = ::std::os::raw::c_int;
pub type ANARIStatusSeverity = ::std::os::raw::c_int;
pub type ANARILibrary = *mut ::std::os::raw::c_void;
pub type ANARIObject = *mut ::std::os::raw::c_void;
pub type ANARIDevice = *mut ::std::os::raw::c_void;
pub type ANARICamera = *mut ::std::os::raw::c_void;
pub type ANARIArray = *mut ::std::os::raw::c_void;
pub type ANARIArray1D = *mut ::std::os::raw::c_void;
pub type ANARIArray2D = *mut ::std::os::raw::c_void;
pub type ANARIArray3D = *mut ::std::os::raw::c_void;
pub type ANARIFrame = *mut ::std::os::raw::c_void;
pub type ANARIFuture = *mut ::std::os::raw::c_void;
pub type ANARIGeometry = *mut ::std::os::raw::c_void;
pub type ANARIGroup = *mut ::std::os::raw::c_void;
pub type ANARIInstance = *mut ::std::os::raw::c_void;
pub type ANARILight = *mut ::std::os::raw::c_void;
pub type ANARIMaterial = *mut ::std::os::raw::c_void;
pub type ANARISampler = *mut ::std::os::raw::c_void;
pub type ANARISurface = *mut ::std::os::raw::c_void;
pub type ANARIRenderer = *mut ::std::os::raw::c_void;
pub type ANARISpatialField = *mut ::std::os::raw::c_void;
pub type ANARIVolume = *mut ::std::os::raw::c_void;
pub type ANARIWorld = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ANARIParameter {
    pub name: *const ::std::os::raw::c_char,
    pub type_: ANARIDataType,
}
#[test]
fn bindgen_test_layout_ANARIParameter() {
    const UNINIT: ::std::mem::MaybeUninit<ANARIParameter> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<ANARIParameter>(),
        16usize,
        concat!("Size of: ", stringify!(ANARIParameter))
    );
    assert_eq!(
        ::std::mem::align_of::<ANARIParameter>(),
        8usize,
        concat!("Alignment of ", stringify!(ANARIParameter))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(ANARIParameter),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(ANARIParameter),
            "::",
            stringify!(type_)
        )
    );
}
pub type ANARIMemoryDeleter = ::std::option::Option<
    unsafe extern "C" fn(
        userPtr: *const ::std::os::raw::c_void,
        appMemory: *const ::std::os::raw::c_void,
    ),
>;
pub type ANARIStatusCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userPtr: *const ::std::os::raw::c_void,
        device: ANARIDevice,
        source: ANARIObject,
        sourceType: ANARIDataType,
        severity: ANARIStatusSeverity,
        code: ANARIStatusCode,
        message: *const ::std::os::raw::c_char,
    ),
>;
pub type ANARIFrameCompletionCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userPtr: *const ::std::os::raw::c_void,
        device: ANARIDevice,
        frame: ANARIFrame,
    ),
>;
extern "C" {
    pub fn anariLoadLibrary(
        name: *const ::std::os::raw::c_char,
        statusCallback: ANARIStatusCallback,
        statusCallbackUserData: *const ::std::os::raw::c_void,
    ) -> ANARILibrary;
}
extern "C" {
    pub fn anariUnloadLibrary(module: ANARILibrary);
}
extern "C" {
    pub fn anariLoadModule(library: ANARILibrary, name: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn anariUnloadModule(library: ANARILibrary, name: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn anariNewDevice(
        library: ANARILibrary,
        type_: *const ::std::os::raw::c_char,
    ) -> ANARIDevice;
}
extern "C" {
    pub fn anariNewArray1D(
        device: ANARIDevice,
        appMemory: *const ::std::os::raw::c_void,
        deleter: ANARIMemoryDeleter,
        userData: *const ::std::os::raw::c_void,
        dataType: ANARIDataType,
        numElements1: u64,
    ) -> ANARIArray1D;
}
extern "C" {
    pub fn anariNewArray2D(
        device: ANARIDevice,
        appMemory: *const ::std::os::raw::c_void,
        deleter: ANARIMemoryDeleter,
        userData: *const ::std::os::raw::c_void,
        dataType: ANARIDataType,
        numElements1: u64,
        numElements2: u64,
    ) -> ANARIArray2D;
}
extern "C" {
    pub fn anariNewArray3D(
        device: ANARIDevice,
        appMemory: *const ::std::os::raw::c_void,
        deleter: ANARIMemoryDeleter,
        userData: *const ::std::os::raw::c_void,
        dataType: ANARIDataType,
        numElements1: u64,
        numElements2: u64,
        numElements3: u64,
    ) -> ANARIArray3D;
}
extern "C" {
    pub fn anariMapArray(device: ANARIDevice, array: ANARIArray) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn anariUnmapArray(device: ANARIDevice, array: ANARIArray);
}
extern "C" {
    pub fn anariNewLight(device: ANARIDevice, type_: *const ::std::os::raw::c_char) -> ANARILight;
}
extern "C" {
    pub fn anariNewCamera(device: ANARIDevice, type_: *const ::std::os::raw::c_char)
        -> ANARICamera;
}
extern "C" {
    pub fn anariNewGeometry(
        device: ANARIDevice,
        type_: *const ::std::os::raw::c_char,
    ) -> ANARIGeometry;
}
extern "C" {
    pub fn anariNewSpatialField(
        device: ANARIDevice,
        type_: *const ::std::os::raw::c_char,
    ) -> ANARISpatialField;
}
extern "C" {
    pub fn anariNewVolume(device: ANARIDevice, type_: *const ::std::os::raw::c_char)
        -> ANARIVolume;
}
extern "C" {
    pub fn anariNewSurface(device: ANARIDevice) -> ANARISurface;
}
extern "C" {
    pub fn anariNewMaterial(
        device: ANARIDevice,
        type_: *const ::std::os::raw::c_char,
    ) -> ANARIMaterial;
}
extern "C" {
    pub fn anariNewSampler(
        device: ANARIDevice,
        type_: *const ::std::os::raw::c_char,
    ) -> ANARISampler;
}
extern "C" {
    pub fn anariNewGroup(device: ANARIDevice) -> ANARIGroup;
}
extern "C" {
    pub fn anariNewInstance(
        device: ANARIDevice,
        type_: *const ::std::os::raw::c_char,
    ) -> ANARIInstance;
}
extern "C" {
    pub fn anariNewWorld(device: ANARIDevice) -> ANARIWorld;
}
extern "C" {
    pub fn anariNewObject(
        device: ANARIDevice,
        objectType: *const ::std::os::raw::c_char,
        type_: *const ::std::os::raw::c_char,
    ) -> ANARIObject;
}
extern "C" {
    pub fn anariSetParameter(
        device: ANARIDevice,
        object: ANARIObject,
        name: *const ::std::os::raw::c_char,
        dataType: ANARIDataType,
        mem: *const ::std::os::raw::c_void,
    );
}
extern "C" {
    pub fn anariUnsetParameter(
        device: ANARIDevice,
        object: ANARIObject,
        name: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn anariUnsetAllParameters(device: ANARIDevice, object: ANARIObject);
}
extern "C" {
    pub fn anariMapParameterArray1D(
        device: ANARIDevice,
        object: ANARIObject,
        name: *const ::std::os::raw::c_char,
        dataType: ANARIDataType,
        numElements1: u64,
        elementStride: *mut u64,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn anariMapParameterArray2D(
        device: ANARIDevice,
        object: ANARIObject,
        name: *const ::std::os::raw::c_char,
        dataType: ANARIDataType,
        numElements1: u64,
        numElements2: u64,
        elementStride: *mut u64,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn anariMapParameterArray3D(
        device: ANARIDevice,
        object: ANARIObject,
        name: *const ::std::os::raw::c_char,
        dataType: ANARIDataType,
        numElements1: u64,
        numElements2: u64,
        numElements3: u64,
        elementStride: *mut u64,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn anariUnmapParameterArray(
        device: ANARIDevice,
        object: ANARIObject,
        name: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn anariCommitParameters(device: ANARIDevice, object: ANARIObject);
}
extern "C" {
    pub fn anariRelease(device: ANARIDevice, object: ANARIObject);
}
extern "C" {
    pub fn anariRetain(device: ANARIDevice, object: ANARIObject);
}
extern "C" {
    pub fn anariGetDeviceSubtypes(library: ANARILibrary) -> *mut *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn anariGetDeviceExtensions(
        library: ANARILibrary,
        deviceSubtype: *const ::std::os::raw::c_char,
    ) -> *mut *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn anariGetObjectSubtypes(
        device: ANARIDevice,
        objectType: ANARIDataType,
    ) -> *mut *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn anariGetObjectInfo(
        device: ANARIDevice,
        objectType: ANARIDataType,
        objectSubtype: *const ::std::os::raw::c_char,
        infoName: *const ::std::os::raw::c_char,
        infoType: ANARIDataType,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn anariGetParameterInfo(
        device: ANARIDevice,
        objectType: ANARIDataType,
        objectSubtype: *const ::std::os::raw::c_char,
        parameterName: *const ::std::os::raw::c_char,
        parameterType: ANARIDataType,
        infoName: *const ::std::os::raw::c_char,
        infoType: ANARIDataType,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn anariGetProperty(
        device: ANARIDevice,
        object: ANARIObject,
        name: *const ::std::os::raw::c_char,
        type_: ANARIDataType,
        mem: *mut ::std::os::raw::c_void,
        size: u64,
        mask: ANARIWaitMask,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn anariNewFrame(device: ANARIDevice) -> ANARIFrame;
}
extern "C" {
    pub fn anariMapFrame(
        device: ANARIDevice,
        frame: ANARIFrame,
        channel: *const ::std::os::raw::c_char,
        width: *mut u32,
        height: *mut u32,
        pixelType: *mut ANARIDataType,
    ) -> *const ::std::os::raw::c_void;
}
extern "C" {
    pub fn anariUnmapFrame(
        device: ANARIDevice,
        frame: ANARIFrame,
        channel: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn anariNewRenderer(
        device: ANARIDevice,
        type_: *const ::std::os::raw::c_char,
    ) -> ANARIRenderer;
}
extern "C" {
    pub fn anariRenderFrame(device: ANARIDevice, frame: ANARIFrame);
}
extern "C" {
    pub fn anariFrameReady(
        device: ANARIDevice,
        frame: ANARIFrame,
        mask: ANARIWaitMask,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn anariDiscardFrame(device: ANARIDevice, frame: ANARIFrame);
}
